version: '3.8'

services:
  # Main RAG Application (Pathway + FastAPI)
  rag-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: business-rag-app
    ports:
      - "8000:8000"  # Pathway RAG API
      - "8001:8001"  # FastAPI Upload/Search API
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - DATA_DIR=/app/data
      - PATHWAY_HOST=0.0.0.0
      - PATHWAY_PORT=8000
    volumes:
      - rag-data:/app/data
      - rag-cache:/app/Cache
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit UI Service
  streamlit-ui:
    build:
      context: .
      dockerfile: dockerfile
    container_name: business-rag-ui
    ports:
      - "8501:8501"  # Streamlit UI
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=http://rag-app:8001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
    volumes:
      - rag-data:/app/data
    networks:
      - rag-network
    restart: unless-stopped
    depends_on:
      rag-app:
        condition: service_healthy
    command: ["streamlit", "run", "ui/main.py", "--server.port=8501", "--server.address=0.0.0.0"]

networks:
  rag-network:
    driver: bridge
    name: business-rag-network

volumes:
  rag-data:
    driver: local
  rag-cache:
    driver: local